import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { uniformClient } from "../src/uniform/uniformClient"
import { enhance } from "@uniformdev/canvas"
import { enhancers } from "../src/enhancers"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>

    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async (
  context
) => {
  const { composition } = await uniformClient.getCompositionBySlug({
    slug: '/home',
  })
  await enhance({ composition, enhancers, context })
  return { props: { composition } }
}
