import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { uniformClient } from '../src/uniform/uniformClient'
import { enhance, ComponentInstance } from '@uniformdev/canvas'
import { enhancers } from '../src/enhancers'

interface HomeProps {
  composition: ComponentInstance
}

const Home: NextPage<HomeProps> = ({ composition }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <pre>
          <code>{JSON.stringify(composition, null, 2)}</code>
        </pre>
      </main>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<HomeProps> = async (
  context
) => {
  const { composition } =
    await uniformClient.getCompositionBySlug({
      slug: '/home',
    })
  await enhance({ composition, enhancers, context })
  return { props: { composition } }
}
